version: "2"
services:
  mailcollector:
      container_name: teamindsMailCollector
      build: .
      environment:
            - USERNAME=test
            - PASSWORD=test
      restart: always
      volumes:
        - datavolume:/usr/src/logs
      ports:
        - 2000:8080
volumes:
    datavolume:

